# Niave bayes algorithm
`NIAVE-BAYES ALGORITHM` is a classification algorithm based on Bayes' theorem with the assumption that any two events are independent given the value of a third event.
`Byes Theorem` is a formula used to calculate the probability of an event given other events, and it is named after the Reverend Thomas Bayes.
also use for find the probability of any events.Formula:
`P(A|B) = P(B|A) * P(A) / P(B)`
where P(A|B) is the probability of event A given event B, P(B|A) is the probability of event B given event A, P(A) is the probability of event A, and P(B) is the probability of event B.
p(B|A) is called the conditional probability of B given A, and p(A|B) is called the conditional probability of A given B.
p(A) is called the prior probability of A, and p(B) is called the prior probability of B.
p(B) is called the prior probability of B, and p(A|B) is called the conditional probability of A given B.

In [5]:
# import libraries
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.naive_bayes import GaussianNB, MultinomialNB, BernoulliNB
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
from sklearn.datasets import load_iris

 



In [11]:
# load iris data and x and y 
iris = load_iris()
x = iris.data
y = iris.target
# train test split data
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)


In [13]:
# train model
model = GaussianNB()
model.fit(x_train,y_train)
# pridict
y_pred=model.predict(x_test)
# evaluate the model
print(classification_report(y_test,y_pred))
print(confusion_matrix(y_test,y_pred))
print(accuracy_score(y_test,y_pred))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        10
           1       1.00      1.00      1.00         9
           2       1.00      1.00      1.00        11

    accuracy                           1.00        30
   macro avg       1.00      1.00      1.00        30
weighted avg       1.00      1.00      1.00        30

[[10  0  0]
 [ 0  9  0]
 [ 0  0 11]]
1.0
